// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface AboutMe {
  id: string;
  slug: string | null;
  status: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  photo_alt?: string;
  about_paragraph_1?: string;
  about_paragraph_2?: string;
  birthday?: string;
  degree?: string;
  location?: string;
  email?: string;
  specialization?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Contact {
  id: string;
  slug: string | null;
  status: string;
  email?: string;
  resume_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Experience {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  company: string;
  date: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Home {
  id: string;
  slug: string | null;
  status: string;
  first_name: string;
  last_name: string;
  title: string;
  intro?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  link?: string;
  icon?: string;
  tags?: unknown;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Skill {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  category: string;
  icon: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about_me: AboutMe;
    contact: Contact;
    experience: Experience;
    home: Home;
    projects: Project;
    skills: Skill;
  }
}