// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface Contact {
  id: string;
  slug: string | null;
  status: string;
  email?: string;
  phone?: string;
  github?: string;
  linkedin?: string;
  resume_link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Experience {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  company: string;
  date: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Profile {
  id: string;
  slug: string | null;
  status: string;
  first_name: string;
  last_name: string;
  title: string;
  intro?: string;
  about_paragraph_1?: string;
  about_paragraph_2?: string;
  birthday?: string;
  degree?: string;
  location?: string;
  email?: string;
  specialization?: string;
  skills_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  link?: string;
  icon?: string;
  tags?: unknown;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Skill {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  category: string;
  icon: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    contact: Contact;
    experience: Experience;
    profile: Profile;
    projects: Project;
    skills: Skill;
  }
}